name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["Push a Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Login to Docker hub
        env:
         DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: sudo docker pull $DOCKER_USER/bikeshare-fastapi
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f bikeshare-fastapi-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: sudo docker run -it -d -p 8001:8001 --name bikeshare-fastapi-container $DOCKER_USER/bikeshare-fastapi
